### PR TITLE
Created Readme.md (Hacktoberfest)

### PR DESCRIPTION
**Pull request by salRoid**

### CODE REVIEW

**Comment by varunj** [comment]
@salRoid it looks great. Can you add actual screenshots and probably some description too?

**Comment by salRoid** [comment]
I can do that , but it would be great if you put those details by yourself as u will be satisfied .
A person who has made the app can express his feelings with these stuff how much hardwork he has done . 
Upload your screenshots to some hosting sites get a url for that image and put that url in screens . I use hostinger for these things.

Just open the Readme.md on your project and add the details .

**Comment by varunj** [comment]
It'll be great if you could do it. I would, obviously, customize it to my needs later.

**Comment by salRoid** [comment]
Close the pull request If you don't like/need it.

**Comment by varunj** [comment]
Required work already done

**Comment by varunj** [comment]
Required work already done

**Pull request closed without merging**
